server:
  port: 8000

spring:
  application:
    name: service-provider

eureka:
  client:
    register-with-eureka: true # 服务注册
    fetch-registry: false # 服务提供方, 这里不检索服务
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}