server:
  port: 9000

spring:
  application:
    name: service-consumer

eureka:
  client:
    register-with-eureka: true # 服务注册
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}